//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-wea-SSD_SERVICE_ID_sd_CDA0Tw4XFl1VNXlI
import { wea as SSD_SERVICE_ID_sd_CDA0Tw4XFl1VNXlI } from './sd-services/wea';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-wea-SSD_SERVICE_ID_sd_CDA0Tw4XFl1VNXlI
SSD_SERVICE_ID_sd_CDA0Tw4XFl1VNXlI,
];
